name: jocaaguraarchetype
description: Starter archetype for Flutter apps with Jocaagura Clean Architecture, cross-cutting BLoCs, theming, and navigation setup.

version: 3.4.1

homepage: https://github.com/jocaagura/jocaaguraarchetype
repository: https://github.com/jocaagura/jocaaguraarchetype

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  jocaagura_domain: ^1.32.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

